### ISSUE TITLE
Display:flex not supported

### ISSUE THREAD

**Issue by ArgTang** [cfjedimaster/brackets-csslint#28]
Marks Display:flex, flex-flow, justify-content and align-items as unknown property

**Comment by cfjedimaster** [comment]
@ArgTang your bug is to CSSLint, not Brackets-CSSLint. You should file it with that project. If they have it fixed there, it just means I need to update my instance of the library.

**Comment by ArgTang** [comment]
@cfjedimaster 
Yes, seems like update to parser lib 2.5 will do the trick, do you want me to open a new issue for this? 
can prob also close #30 when updating.

**Comment by cfjedimaster** [comment]
No need - checking now.

**Comment by ArgTang** [comment]
Cool. thanks!

**Comment by cfjedimaster** [comment]
Using the latest CSSLint now. Not saying it fixes your issues, but it is updated at least.

**Comment by ArgTang** [comment]
hmm

**Comment by ArgTang** [comment]
hmm
still not there:  says /* Version v0.2.3, Build time: 19-June-2013 11:16:15 */ in csslint.js

https://github.com/cfjedimaster/brackets-csslint/blob/master/csslint/csslint.js

0.2.5 available here
https://github.com/CSSLint/parser-lib/releases

**Comment by cfjedimaster** [comment]
Hmm. I downloaded the latest and got a copy from "release". Do you see
different?

On Sun, Jan 4, 2015 at 9:05 AM, ArgTang <notifications@github.com> wrote:

> hmm
> still not there: says /* Version v0.2.3, Build time: 19-June-2013 11:16:15
> */ in csslint.js
>
>
> https://github.com/cfjedimaster/brackets-csslint/blob/master/csslint/csslint.js
>
> 0.2.5 available here
> https://github.com/CSSLint/parser-lib/releases
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cfjedimaster/brackets-csslint/issues/28#issuecomment-68635783>
> .
>



-- 
===========================================================================
Raymond Camden, Web Standards Evangelist

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden

**Comment by cfjedimaster** [comment]
See: https://github.com/CSSLint/csslint/blob/master/release/csslint.js

It matches afaik.

On Sun, Jan 4, 2015 at 9:13 AM, Raymond Camden <raymondcamden@gmail.com>
wrote:

> Hmm. I downloaded the latest and got a copy from "release". Do you see
> different?
>
> On Sun, Jan 4, 2015 at 9:05 AM, ArgTang <notifications@github.com> wrote:
>
>> hmm
>> still not there: says /* Version v0.2.3, Build time: 19-June-2013
>> 11:16:15 */ in csslint.js
>>
>>
>> https://github.com/cfjedimaster/brackets-csslint/blob/master/csslint/csslint.js
>>
>> 0.2.5 available here
>> https://github.com/CSSLint/parser-lib/releases
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/cfjedimaster/brackets-csslint/issues/28#issuecomment-68635783>
>> .
>>
>
>
>
> --
> ===========================================================================
> Raymond Camden, Web Standards Evangelist
>
> Email : raymondcamden@gmail.com
> Blog : www.raymondcamden.com
> Twitter: raymondcamden
>



-- 
===========================================================================
Raymond Camden, Web Standards Evangelist

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden

**Comment by ArgTang** [comment]
You are right. csslint use parser-lib 2.3 even though they have 2.4 in the build file. i'll have filed a report in csslint, ill post a message to you if it gets updated.

**Comment by ArgTang** [comment]
I somehow managed to build csslint with grunt myself (wohoo), so theres a new build of it in my fork

https://github.com/ArgTang/brackets-csslint/tree/master/csslint

I can create a pull request if you like. Seems like building ourself is the only way to get the new version.

**Comment by cfjedimaster** [comment]
Seems ok to me.

On Sun, Jan 4, 2015 at 10:00 AM, ArgTang <notifications@github.com> wrote:

> I somehow managed to build csslint with grunt myself (wohoo), so theres a
> new build of it in my fork
>
> https://github.com/ArgTang/brackets-csslint/tree/master/csslint
>
> I can create a pull request if you like. Seems like building ourself is
> the only way to get the new version.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cfjedimaster/brackets-csslint/issues/28#issuecomment-68637628>
> .
>



-- 
===========================================================================
Raymond Camden, Web Standards Evangelist

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden
