### ISSUE TITLE
depreceate box and flexbox

### ISSUE THREAD

**Issue by ArgTang** [cfjedimaster/brackets-csslint#30]
since flex is the new standard for these elements, maybe give feedback to switch to flex

http://stackoverflow.com/questions/16280040/css3-flexbox-display-box-vs-flexbox-vs-flex

**Comment by cfjedimaster** [comment]
@ArgTang your bug is to CSSLint, not Brackets-CSSLint. You should file it with that project. If they have it fixed there, it just means I need to update my instance of the library.

**Comment by ArgTang** [comment]
updating parser lib will probably fix this

**Comment by cfjedimaster** [comment]
I'll see how far behind I am and will update.
