### ISSUE TITLE
How do you build the csslint.js file?

### ISSUE THREAD

**Issue by wcandillon** [cfjedimaster/brackets-csslint#33]
I would like my brackets extension to embed xqlint the same way this project is embedding csslint. Can you explain me how you build the csslint.js file?

**Comment by cfjedimaster** [comment]
It came from a third party project. Am I misunderstanding your question?

On Sun, Jan 4, 2015 at 1:55 PM, William Candillon <notifications@github.com>
wrote:

> I would like my brackets extension to embed xqlint the same way this
> project is embedding csslint. Can you explain me how you build the
> csslint.js file?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cfjedimaster/brackets-csslint/issues/33>.
>



-- 
===========================================================================
Raymond Camden, Web Standards Evangelist

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden

**Comment by wcandillon** [comment]
the csslint.js file in your repo is built from the csslint npm package. How did you do it? It's doesn't look like a browserified file.

I'm trying to build a brackets plugin that depends on a thrid party npm package (like you did with csslint) and I am not sure how to do it.

**Comment by cfjedimaster** [comment]
Check the history - another user did it for me :)

On Sun, Jan 4, 2015 at 3:56 PM, William Candillon <notifications@github.com>
wrote:

> the csslint.js file in your repo is built from the csslint npm package.
> How did you do it? It's doesn't look like a browserified file.
>
> I'm trying to build a brackets plugin that depends on a thrid party npm
> package (like you did with csslint) and I am not sure how to do it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cfjedimaster/brackets-csslint/issues/33#issuecomment-68651131>
> .
>



-- 
===========================================================================
Raymond Camden, Web Standards Evangelist

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden

**Comment by wcandillon** [comment]
@ArgTang Maybe you can help me? :)

**Comment by ArgTang** [comment]
open comandline in the csslint folder.
install grunt: npm install -g grunt-cli
then i used npm install (not shure its needed)
then npm grunt will build the project, and put it in a folder.
you also need to edit the package.json file to get the latest parselib. Im not sure how to get it minified version.

**Comment by wcandillon** [comment]
@ArgTang Thks a lot!
