### ISSUE TITLE
Why is alpha order for rule properties required?

### ISSUE THREAD

**Issue by AllThingsSmitty** [cfjedimaster/brackets-csslint#36]
I noticed the recent update now flags CSS rules that don't have properties in alphabetical order. Requiring a specific order of properties seems unnecessary for a linter, especially if you're using other tools like CSSComb and pre-determining a preferred order.

![csslintproblems](https://cloud.githubusercontent.com/assets/1682367/5782447/ec4732a6-9d88-11e4-81cd-261d1ab35b9f.png)

Can this feature be a toggle switch for preferences on the linter?

**Comment by cfjedimaster** [comment]
If it can be modded by .csslintrc, then sure. Otherwise you have to bring it up with the CSSLint folks. My code just wraps theirs and makes it work in Brackets.

**Comment by AllThingsSmitty** [comment]
@cfjedimaster thanks, I'll check into that on their end.
