### ISSUE TITLE
[Suggestion] Replace alphabetical order with logic order

### ISSUE THREAD

**Issue by ShinDarth** [cfjedimaster/brackets-csslint#38]
What about replacing the requirement of having css rules in alphabetical order with a logic one like http://codeguide.co/#css-declaration-order

I think alphabetical order could be muddler sometimes.

**Comment by cfjedimaster** [comment]
That isn't my extension, but rather CSSLint itself.

**Comment by Lichtjaeger** [comment]
Use a .csslintrc file with  "order-alphabetical": false  to suppress warnings about alphabetical order.

**Comment by cfjedimaster** [comment]
Thanks @Lichtjaeger
