### ISSUE TITLE
Missing semicolon not linting in css

### ISSUE THREAD

**Issue by Srcky** [cfjedimaster/brackets-csslint#44]
When there is only one property for a certain selector, and it's missing a semicolon, CSSLint won't show it as error. For instance:
a {
color: #0083e8
}
This won't show as error.

**Comment by cfjedimaster** [comment]
If the 'real' CSSLint doesn't report it, my extension won't either. What do you see when you test it at their site?

**Comment by Srcky** [comment]
Just tried it, seems it doesn't show error either!

**Comment by cfjedimaster** [comment]
File a bug on their side. When they fix and release, the extension here can be updated.
